all: ers

ers:main.o employeerecordsystem.o
	gcc -Wall -o ers main.o employeerecordsystem.o

main.o:main.c
	gcc -c -Wall main.c

employeerecordsystem.o:employeerecordsystem.c
	gcc -c -Wall employeerecordsystem.c


